# Generated by Django 5.2.12 on 2026-03-26 18:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('matrix', 'Пространственные матрицы'), ('num_series', 'Числовые ряды'), ('verbal', 'Вербальная логика'), ('other', 'Другое')], max_length=20, verbose_name='Тип задачи')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Текст задачи')),
                ('image_content', models.ImageField(blank=True, null=True, upload_to='tasks/', verbose_name='Изображение задачи')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Правильный ответ')),
                ('estimated_weight', models.FloatField(default=1.0, verbose_name='Предполагаемый вес сложности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('sphere', models.CharField(blank=True, choices=[('tech', 'Техническая / IT'), ('humanities', 'Гуманитарная'), ('natural', 'Естественные науки'), ('student', 'Учащийся / Студент'), ('other', 'Другое')], max_length=20, null=True, verbose_name='Сфера деятельности')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало теста')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание теста')),
            ],
            options={
                'verbose_name': 'Сессия тестирования',
                'verbose_name_plural': 'Сессии тестирования',
            },
        ),
        migrations.CreateModel(
            name='AnswerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=255, verbose_name='Ответ пользователя')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верно')),
                ('time_spent_seconds', models.FloatField(verbose_name='Затраченное время (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='iq_test.task', verbose_name='Задача')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='iq_test.testsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Лог ответа',
                'verbose_name_plural': 'Логи ответов',
                'unique_together': {('session', 'task')},
            },
        ),
    ]
