# Generated by Django 5.2.12 on 2026-03-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iq_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='option_1',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/options/', verbose_name='Вариант 1'),
        ),
        migrations.AddField(
            model_name='task',
            name='option_2',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/options/', verbose_name='Вариант 2'),
        ),
        migrations.AddField(
            model_name='task',
            name='option_3',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/options/', verbose_name='Вариант 3'),
        ),
        migrations.AddField(
            model_name='task',
            name='option_4',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/options/', verbose_name='Вариант 4'),
        ),
        migrations.AddField(
            model_name='task',
            name='option_5',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/options/', verbose_name='Вариант 5'),
        ),
        migrations.AddField(
            model_name='task',
            name='option_6',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/options/', verbose_name='Вариант 6'),
        ),
        migrations.AddField(
            model_name='task',
            name='option_7',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/options/', verbose_name='Вариант 7'),
        ),
        migrations.AddField(
            model_name='task',
            name='option_8',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/options/', verbose_name='Вариант 8'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/main/', verbose_name='Главное изображение (условие)'),
        ),
    ]
