# Generated by Django 5.2.12 on 2026-03-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iq_test', '0003_alter_task_image_content_alter_task_option_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='estimated_ability',
            field=models.FloatField(default=0.0, verbose_name='Оценка способности (θ)'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='standard_error',
            field=models.FloatField(default=3.0, verbose_name='Текущая погрешность'),
        ),
    ]
