# Generated by Django 5.2.11 on 2026-03-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iq_test', '0011_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Lines', 'Линии'), ('Half lines', 'половины линий'), ('crosing lines', 'пересекающиеся линии'), ('rotating shapes', 'вращающиеся фигуры'), ('split vertical grid', 'разделенная вертикальная сетка'), ('radial lines', 'радиальные линии'), ('umnojenie drobei', 'умножение дробей'), ('interactions figures', 'взаимодействия фигур'), ('circles and dots', 'круги и точки'), ('3x3 grid', '3х3 сетка'), ('other', 'Другое')], max_length=20, verbose_name='Тип задачи'),
        ),
    ]
