# Generated by Django 5.2.11 on 2026-04-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iq_test', '0017_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Lines', 'Линии'), ('Half lines', 'половины линий'), ('crosing lines', 'пересекающиеся линии'), ('rotating shapes', 'вращающиеся фигуры'), ('split vertical grid', 'разделенная вертикальная сетка'), ('radial lines', 'радиальные линии'), ('umnojenie drobei', 'умножение дробей'), ('interactions figures', 'взаимодействия фигур'), ('circles and dots', 'круги и точки'), ('3x3 grid', '3х3 сетка'), ('logical swap', 'логический обмен'), ('cubes reflections', 'кубы и отражения'), ('rotating dot hexagon', 'вращающаяся точка в шестиугольнике'), ('line XOR logic', 'логика ИЛИ для линий'), ('polygon sides toggle', 'переключение сторон многоугольника'), ('clock hands rotation', 'вращение стрелок часов'), ('Dot Set Union', 'Объединение множеств точек'), ('Square Line Logic A', 'Логика квадратных линий A'), ('Square Line Logic B', 'Логика квадратных линий B'), ('Square Line Logic C', 'Логика квадратных линий C'), ('Square Line Logic D', 'Логика квадратных линий D'), ('Square Line Logic E', 'Логика квадратных линий E'), ('Fill Square', 'Заполнение квадрата'), ('distributed figures', 'распределенные фигуры'), ('other', 'Другое')], max_length=20, verbose_name='Тип задачи'),
        ),
    ]
